export type Part = "d_carrier" | "d_chronic" | "d_broker" | "d_wage";

export type Row = {
  rank: number;
  name: string;
  state: string;
  city: string;
  emp: number;
  total: number;
  pe: number;
  grade: string;
  score: number;
  carrier: string;
  vsm: string;
  broker: string;
  dom: Part;
  domLabel: string;
  parts: Record<Part, number>;
  note: string;
  aka: string;
  cav: string;
  ein: string;
};

export const ROWS: Row[] = [
  {
    rank: 1,
    name: "Trinity Solar, Llc",
    state: "NJ",
    city: "Wall",
    emp: 3110,
    total: 18333736,
    pe: 5895,
    grade: "D",
    score: 14,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Edgewood Partners Insurance Center",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 18253787,
      d_chronic: 0,
      d_broker: 79949,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "223292324",
  },
  {
    rank: 2,
    name: "Tesla, Inc.",
    state: "CA",
    city: "Palo Alto",
    emp: 73107,
    total: 16857793,
    pe: 231,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Bsc Agency Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 15340855,
      d_broker: 1516938,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "912197729",
  },
  {
    rank: 3,
    name: "Marksman Security Corporation",
    state: "FL",
    city: "Fort Lauderdale",
    emp: 2687,
    total: 16165737,
    pe: 6016,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "1.45",
    broker: "Lockton Companies",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 15771037,
      d_chronic: 332696,
      d_broker: 62004,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "020725791",
  },
  {
    rank: 4,
    name: "Dassault Falcon Jet Corporation",
    state: "NJ",
    city: "Little Ferry",
    emp: 2398,
    total: 14074785,
    pe: 5869,
    grade: "D",
    score: 34,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 14074785,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "221978098",
  },
  {
    rank: 5,
    name: "Concurrent Hro, Llc",
    state: "CO",
    city: "Broomfield",
    emp: 2315,
    total: 13641906,
    pe: 5893,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Gbs Benefits Inc.",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 13587626,
      d_chronic: 0,
      d_broker: 54280,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "475137893",
  },
  {
    rank: 6,
    name: "National Debt Relief Llc",
    state: "NY",
    city: "New York",
    emp: 2217,
    total: 13012426,
    pe: 5869,
    grade: "D",
    score: 22,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 13012426,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "271182232",
  },
  {
    rank: 7,
    name: "Hub Group, Inc.",
    state: "IL",
    city: "Oak Brook",
    emp: 4405,
    total: 11927488,
    pe: 2708,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Marsh & Mclennan Agency Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 7653156,
      d_broker: 1888775,
      d_wage: 2385557,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "364007085",
  },
  {
    rank: 8,
    name: "Inter-Con Security Systems, Inc.",
    state: "CA",
    city: "Pasadena",
    emp: 2591,
    total: 11849349,
    pe: 4573,
    grade: "D",
    score: 36,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 11849349,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "953020192",
  },
  {
    rank: 9,
    name: "Academic Medical Group",
    state: "FL",
    city: "Tampa",
    emp: 1739,
    total: 11354558,
    pe: 6529,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 5576872,
      d_broker: 2120147,
      d_wage: 3657539,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "863038188",
  },
  {
    rank: 10,
    name: "Ati Payroll Services, Llc",
    state: "CA",
    city: "Anaheim",
    emp: 1931,
    total: 11333782,
    pe: 5869,
    grade: "D",
    score: 34,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 11333782,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "932003212",
  },
  {
    rank: 11,
    name: "Trueblue, Inc.",
    state: "WA",
    city: "Tacoma",
    emp: 3986,
    total: 11292496,
    pe: 2833,
    grade: "D",
    score: 37,
    carrier: "",
    vsm: "",
    broker: "Eoi Service Company, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 9027479,
      d_broker: 645050,
      d_wage: 1619967,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "911287341",
  },
  {
    rank: 12,
    name: "Highmark Health",
    state: "PA",
    city: "Pittsburgh",
    emp: 13164,
    total: 10971663,
    pe: 833,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Sedgwick Claims Management Services",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 9065301,
      d_broker: 1906362,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "453674900",
  },
  {
    rank: 13,
    name: "Leidos Biomedical Research, Inc.",
    state: "MD",
    city: "Frederick",
    emp: 2393,
    total: 10261759,
    pe: 4288,
    grade: "D",
    score: 34,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Bolton Partners, Inc.",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 10255515,
      d_chronic: 0,
      d_broker: 6244,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "330653185",
  },
  {
    rank: 14,
    name: "Flagship Facility Services, Llc",
    state: "TX",
    city: "Southlake",
    emp: 1696,
    total: 10029652,
    pe: 5914,
    grade: "D",
    score: 44,
    carrier: "",
    vsm: "1.45",
    broker: "Edgewood Partners Insurance Center",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 9954477,
      d_chronic: 0,
      d_broker: 75175,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "first_year_lines",
    ein: "921160337",
  },
  {
    rank: 15,
    name: "Forest River, Inc.",
    state: "IN",
    city: "Elkhart",
    emp: 10511,
    total: 9418481,
    pe: 896,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gibson Insurance Agency, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 8556389,
      d_broker: 862092,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "203284366",
  },
  {
    rank: 16,
    name: "Tri Star Services, Llc",
    state: "TN",
    city: "Nashville",
    emp: 1573,
    total: 9266655,
    pe: 5891,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "1.45",
    broker: "Willis Towers Watson Southeast Inc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 9232543,
      d_chronic: 0,
      d_broker: 34112,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "621828852",
  },
  {
    rank: 17,
    name: "Erigo Inc.",
    state: "KY",
    city: "Ft Mitchell",
    emp: 430,
    total: 9107230,
    pe: 21180,
    grade: "C",
    score: 66,
    carrier: "",
    vsm: "",
    broker: "Business Benefits, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 9100218,
      d_broker: 7012,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "452569924",
  },
  {
    rank: 18,
    name: "Hazen And Sawyer",
    state: "NY",
    city: "New York",
    emp: 1881,
    total: 8956411,
    pe: 4762,
    grade: "D",
    score: 14,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Rsc Insurance Brokerage Inc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 8949698,
      d_chronic: 0,
      d_broker: 6713,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "132904652",
  },
  {
    rank: 19,
    name: "Quinn Emanuel Urquhart & Sullivan, Llp",
    state: "CA",
    city: "Los Angeles",
    emp: 1370,
    total: 8295913,
    pe: 6055,
    grade: "D",
    score: 14,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Barkley, An Alera Insurance Agency",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 8281255,
      d_chronic: 0,
      d_broker: 14658,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "954004138",
  },
  {
    rank: 20,
    name: "Rockefeller Health & Welfare Benefits Trust",
    state: "NY",
    city: "New York",
    emp: 3137,
    total: 7936100,
    pe: 2530,
    grade: "D",
    score: 22,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Aon Consulting Inc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 7882994,
      d_chronic: 0,
      d_broker: 53106,
      d_wage: 0,
    },
    note: "Multiple-employer trust \u2014 participants span several employers",
    aka: "",
    cav: "",
    ein: "806076929",
  },
  {
    rank: 21,
    name: "Paramount Residential Mortgage Group",
    state: "CA",
    city: "Corona",
    emp: 1261,
    total: 7382489,
    pe: 5854,
    grade: "D",
    score: 22,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "Willis Towers Watson West Inc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 5766897,
      d_chronic: 1554123,
      d_broker: 61469,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "330975529",
  },
  {
    rank: 22,
    name: "Sepa Associates, Llc",
    state: "PA",
    city: "Philadelphia",
    emp: 1142,
    total: 6702838,
    pe: 5869,
    grade: "D",
    score: 14,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 6702838,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "821644143",
  },
  {
    rank: 23,
    name: "22Nd Century Technologies, Inc.",
    state: "VA",
    city: "Mclean",
    emp: 1100,
    total: 6456323,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 6456323,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "223502121",
  },
  {
    rank: 24,
    name: "Innovative Employee Solutions",
    state: "CA",
    city: "San Diego",
    emp: 1383,
    total: 6324836,
    pe: 4573,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "1.32",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 6324836,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "840841199",
  },
  {
    rank: 25,
    name: "Hy-Vee, Inc.",
    state: "IA",
    city: "West Des Moines",
    emp: 16093,
    total: 6147767,
    pe: 382,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "Midwest Heritage Services, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 5899801,
      d_broker: 247966,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "420325638",
  },
  {
    rank: 26,
    name: "Pacific Architects And Engineers, Llc",
    state: "VA",
    city: "Falls Church",
    emp: 2799,
    total: 6114604,
    pe: 2185,
    grade: "D",
    score: 50,
    carrier: "",
    vsm: "",
    broker: "Willis Towers Watson Us Llc",
    dom: "d_wage",
    domLabel: "Wage",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 2755442,
      d_wage: 3359162,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "980000105",
  },
  {
    rank: 27,
    name: "Legal & General America, Inc.",
    state: "MD",
    city: "Frederick",
    emp: 1020,
    total: 5999143,
    pe: 5882,
    grade: "D",
    score: 14,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Nfp Corporate Services Pa",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 5986773,
      d_chronic: 0,
      d_broker: 12370,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "521236150",
  },
  {
    rank: 28,
    name: "Ripa And Associates Llc",
    state: "FL",
    city: "Tampa",
    emp: 966,
    total: 5985887,
    pe: 6197,
    grade: "C",
    score: 60,
    carrier: "",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 5669826,
      d_chronic: 316061,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "593497167",
  },
  {
    rank: 29,
    name: "Sei Group",
    state: "GA",
    city: "Doraville",
    emp: 895,
    total: 5604211,
    pe: 6262,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Usi Insurance Services Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 5253100,
      d_chronic: 287355,
      d_broker: 63756,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "582478990",
  },
  {
    rank: 30,
    name: "Carmax, Inc.",
    state: "VA",
    city: "Richmond",
    emp: 29611,
    total: 5424973,
    pe: 183,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "Sedgwick Claims Management Services",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 5133517,
      d_broker: 291456,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "541821055",
  },
  {
    rank: 31,
    name: "Tricon American Homes",
    state: "CA",
    city: "Tustin",
    emp: 913,
    total: 5415396,
    pe: 5931,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Marsh & Mclennan Agency Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 5358748,
      d_chronic: 0,
      d_broker: 56648,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "471254912",
  },
  {
    rank: 32,
    name: "Texas Roadhouse Management Corp.",
    state: "KY",
    city: "Louisville",
    emp: 7427,
    total: 5131929,
    pe: 691,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Lockton Companies, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3317202,
      d_broker: 791320,
      d_wage: 1023407,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "611316260",
  },
  {
    rank: 33,
    name: "The Haskell Company",
    state: "FL",
    city: "Jacksonville",
    emp: 1452,
    total: 5041170,
    pe: 3472,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Saunders Benefits Consulting, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3439032,
      d_broker: 31718,
      d_wage: 1570420,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "592387450",
  },
  {
    rank: 34,
    name: "Legacy Healthcare Financial Services Llc",
    state: "IL",
    city: "Skokie",
    emp: 6093,
    total: 4964651,
    pe: 815,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Davidson James Duncan",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 4673584,
      d_broker: 291067,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "263151856",
  },
  {
    rank: 35,
    name: "Tri City Foods, Inc.",
    state: "IL",
    city: "Downers Grove",
    emp: 1804,
    total: 4886032,
    pe: 2708,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Rockwell & Associates Ltd",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3403100,
      d_broker: 264671,
      d_wage: 1218261,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "471813575",
  },
  {
    rank: 36,
    name: "Axonics Modulation Technology, Inc.",
    state: "CA",
    city: "Irvine",
    emp: 825,
    total: 4842243,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4842243,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "Axonics, Inc. (filed as Axonics Modulation Technology, Inc.)",
    cav: "",
    ein: "454744083",
  },
  {
    rank: 37,
    name: "C3.Ai, Inc.",
    state: "CA",
    city: "Redwood City",
    emp: 818,
    total: 4801157,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4801157,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "263999357",
  },
  {
    rank: 38,
    name: "Sunset Aviation, Llc",
    state: "CA",
    city: "Petaluma",
    emp: 1400,
    total: 4764646,
    pe: 3403,
    grade: "D",
    score: 34,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4764646,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "Solairus Aviation (filed as Sunset Aviation, LLC)",
    cav: "",
    ein: "800319107",
  },
  {
    rank: 39,
    name: "Punahou School",
    state: "HI",
    city: "Honolulu",
    emp: 978,
    total: 4682596,
    pe: 4788,
    grade: "C",
    score: 64,
    carrier: "",
    vsm: "",
    broker: "Mercer Health & Benefits, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 4644031,
      d_broker: 38565,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "990073523",
  },
  {
    rank: 40,
    name: "Newcold Seattle Operations",
    state: "WA",
    city: "Tacoma",
    emp: 726,
    total: 4542491,
    pe: 6257,
    grade: "D",
    score: 44,
    carrier: "Cambia Health",
    vsm: "1.49",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4542491,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "810995900",
  },
  {
    rank: 41,
    name: "Out West Restaurant Group",
    state: "CA",
    city: "San Diego",
    emp: 982,
    total: 4496920,
    pe: 4579,
    grade: "C",
    score: 60,
    carrier: "",
    vsm: "1.32",
    broker: "Marsh & Mclennan Agency Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4490954,
      d_chronic: 0,
      d_broker: 5966,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "330600849",
  },
  {
    rank: 42,
    name: "Perkins Eastman Architects, D.P.C.",
    state: "NY",
    city: "New York",
    emp: 751,
    total: 4415150,
    pe: 5879,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Nfp Corporate Services Ny Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4407908,
      d_chronic: 0,
      d_broker: 7242,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "133044005",
  },
  {
    rank: 43,
    name: "Surgery Partners, Inc.",
    state: "TN",
    city: "Brentwood",
    emp: 7123,
    total: 4374512,
    pe: 614,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3671676,
      d_broker: 702836,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "473620923",
  },
  {
    rank: 44,
    name: "Gap Solutions, Inc.",
    state: "VA",
    city: "Herndon",
    emp: 744,
    total: 4366822,
    pe: 5869,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4366822,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "541903817",
  },
  {
    rank: 45,
    name: "Cpc Logistics Inc.",
    state: "MO",
    city: "Chesterfield",
    emp: 2894,
    total: 4365695,
    pe: 1509,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Lockton Companies, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2575390,
      d_broker: 813605,
      d_wage: 976700,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "431412670",
  },
  {
    rank: 46,
    name: "P. O. Y. Holdings, Llc",
    state: "NJ",
    city: "Totowa",
    emp: 972,
    total: 4302294,
    pe: 4426,
    grade: "C",
    score: 66,
    carrier: "",
    vsm: "",
    broker: "",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 4302294,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "204159078",
  },
  {
    rank: 47,
    name: "New Prime, Inc.",
    state: "MO",
    city: "Springfield",
    emp: 2610,
    total: 4255722,
    pe: 1631,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3333399,
      d_broker: 0,
      d_wage: 922323,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "431396933",
  },
  {
    rank: 48,
    name: "Nebraska Methodist Health Syst, Inc",
    state: "NE",
    city: "Omaha",
    emp: 5470,
    total: 4240414,
    pe: 775,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Bcinsourcing Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3552936,
      d_broker: 687478,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "470639839",
  },
  {
    rank: 49,
    name: "Lymi, Inc. Dba Reformation",
    state: "CA",
    city: "Vernon",
    emp: 714,
    total: 4190741,
    pe: 5869,
    grade: "D",
    score: 44,
    carrier: "",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4190741,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "352467049",
  },
  {
    rank: 50,
    name: "Bobrick Washroom Equipment Inc.",
    state: "CA",
    city: "North Hollywood",
    emp: 703,
    total: 4126178,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 4126178,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "951763946",
  },
  {
    rank: 51,
    name: "Wayne Farms Llc",
    state: "GA",
    city: "Oakwood",
    emp: 24207,
    total: 4111120,
    pe: 170,
    grade: "D",
    score: 54,
    carrier: "",
    vsm: "",
    broker: "Bcinsourcing Llc",
    dom: "d_broker",
    domLabel: "Broker",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 4111120,
      d_wage: 0,
    },
    note: "Findings are on ancillary/voluntary benefits; no medical (4A) coverage on file",
    aka: "",
    cav: "",
    ein: "582530930",
  },
  {
    rank: 52,
    name: "Volvo Construction Equipment North America, Llc",
    state: "PA",
    city: "Shippensburg",
    emp: 285,
    total: 4103219,
    pe: 14397,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Mercer Health & Benefits Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3093981,
      d_broker: 139350,
      d_wage: 869888,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "382496821",
  },
  {
    rank: 53,
    name: "Intat Precision, Inc.",
    state: "IN",
    city: "Rushville",
    emp: 272,
    total: 4020238,
    pe: 14780,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services Inc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2741760,
      d_broker: 319992,
      d_wage: 958486,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "581773607",
  },
  {
    rank: 54,
    name: "Senior Lifestyle Dc, Llc",
    state: "IL",
    city: "Chicago",
    emp: 3846,
    total: 4014927,
    pe: 1044,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "Eoi Service Company Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3286003,
      d_broker: 728924,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "261368051",
  },
  {
    rank: 55,
    name: "Pinkerton Consulting And Investigations, Inc.",
    state: "MI",
    city: "Ann Arbor",
    emp: 865,
    total: 3955881,
    pe: 4573,
    grade: "D",
    score: 36,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3955881,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "954753424",
  },
  {
    rank: 56,
    name: "Attc Manufacturing, Inc.",
    state: "IN",
    city: "Tell City",
    emp: 546,
    total: 3938190,
    pe: 7213,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services Inc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2468132,
      d_broker: 511572,
      d_wage: 958486,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "352122103",
  },
  {
    rank: 57,
    name: "Document Storage Systems, Inc.",
    state: "FL",
    city: "Juno Beach",
    emp: 669,
    total: 3926619,
    pe: 5869,
    grade: "D",
    score: 36,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3926619,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "431575286",
  },
  {
    rank: 58,
    name: "U.S. Committee For Refugees And Immigrants",
    state: "VA",
    city: "Arlington",
    emp: 646,
    total: 3850649,
    pe: 5961,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Hub International Mid-Atlantic",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3791623,
      d_chronic: 0,
      d_broker: 59026,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "131878704",
  },
  {
    rank: 59,
    name: "Worksmart Systems, Inc.",
    state: "IN",
    city: "Indianapolis",
    emp: 10616,
    total: 3846048,
    pe: 362,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3846048,
      d_broker: 0,
      d_wage: 0,
    },
    note: "Multiple-employer plan \u2014 participants span several employers",
    aka: "",
    cav: "short_panel",
    ein: "352060071",
  },
  {
    rank: 60,
    name: "East Penn Manufacturing Co., Inc.",
    state: "PA",
    city: "Lyon Station",
    emp: 9109,
    total: 3786265,
    pe: 416,
    grade: "D",
    score: 38,
    carrier: "",
    vsm: "",
    broker: "Sedgwick Claims Management Svcs Inc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3124828,
      d_broker: 661437,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "231315454",
  },
  {
    rank: 61,
    name: "Memorial Health System",
    state: "IL",
    city: "Springfield",
    emp: 7091,
    total: 3750780,
    pe: 529,
    grade: "D",
    score: 54,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3393448,
      d_broker: 357332,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "371110690",
  },
  {
    rank: 62,
    name: "Sees Candy Shops Incorporated",
    state: "CA",
    city: "South San Francisco",
    emp: 637,
    total: 3738798,
    pe: 5869,
    grade: "D",
    score: 48,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3738798,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "951205740",
  },
  {
    rank: 63,
    name: "Davita Inc.",
    state: "CO",
    city: "Denver",
    emp: 57028,
    total: 3632237,
    pe: 64,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "Sedgwick Claims Management Svcs.",
    dom: "d_broker",
    domLabel: "Broker",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 3632237,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "510354549",
  },
  {
    rank: 64,
    name: "The West Clinic, Pllc",
    state: "TN",
    city: "Germantown",
    emp: 611,
    total: 3602082,
    pe: 5895,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Higginbotham Insurance Agency",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3586194,
      d_chronic: 0,
      d_broker: 15888,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "621526296",
  },
  {
    rank: 65,
    name: "Ta Chen International, Inc.",
    state: "CA",
    city: "Long Beach",
    emp: 613,
    total: 3597933,
    pe: 5869,
    grade: "D",
    score: 48,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3597933,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "954230028",
  },
  {
    rank: 66,
    name: "Finfrock Holdings, Inc.",
    state: "FL",
    city: "Apopka",
    emp: 612,
    total: 3592064,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3592064,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "592954885",
  },
  {
    rank: 67,
    name: "Innospec (Independence Oilfield Chemicals, Llc)",
    state: "TX",
    city: "The Woodlands",
    emp: 751,
    total: 3557117,
    pe: 4737,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Inservices, Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3511656,
      d_chronic: 0,
      d_broker: 45461,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "455239537",
  },
  {
    rank: 68,
    name: "Dobbs Equipment, Llc",
    state: "FL",
    city: "Riverview",
    emp: 605,
    total: 3550978,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3550978,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "822505079",
  },
  {
    rank: 69,
    name: "Boyd Gaming Corporation",
    state: "NV",
    city: "Las Vegas",
    emp: 8735,
    total: 3538786,
    pe: 405,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "The Orientation Company, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3102864,
      d_broker: 435922,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "880242733",
  },
  {
    rank: 70,
    name: "Murphy-Hoffman Company Llc",
    state: "KS",
    city: "Leawood",
    emp: 3542,
    total: 3520943,
    pe: 994,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3520943,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "431394729",
  },
  {
    rank: 71,
    name: "Atos It Solutions And Services, Inc.",
    state: "TX",
    city: "Plano",
    emp: 2180,
    total: 3519105,
    pe: 1614,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Usi Insurance Services Llc",
    dom: "d_wage",
    domLabel: "Wage",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 32957,
      d_wage: 3486148,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "133715291",
  },
  {
    rank: 72,
    name: "North American Automotive Services, Inc.",
    state: "IL",
    city: "Oakbrook Terrace",
    emp: 5595,
    total: 3516568,
    pe: 629,
    grade: "C",
    score: 61,
    carrier: "",
    vsm: "",
    broker: "Eoi Service Company",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3127723,
      d_broker: 388845,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "363796094",
  },
  {
    rank: 73,
    name: "Stormont-Vail Healthcare Inc",
    state: "KS",
    city: "Topeka",
    emp: 5747,
    total: 3513196,
    pe: 611,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Lockton Companies, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2945859,
      d_broker: 567337,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "480543789",
  },
  {
    rank: 74,
    name: "Reliance Health Care, Inc.",
    state: "AR",
    city: "Conway",
    emp: 1313,
    total: 3494710,
    pe: 2662,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Acrisure, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2422795,
      d_broker: 408435,
      d_wage: 663480,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "261622769",
  },
  {
    rank: 75,
    name: "Industrial Inspection & Analysis, Inc.",
    state: "MN",
    city: "Minnetonka",
    emp: 595,
    total: 3492284,
    pe: 5869,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3492284,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "473920420",
  },
  {
    rank: 76,
    name: "Staar Surgical Company, Inc.",
    state: "CA",
    city: "Monrovia",
    emp: 756,
    total: 3492069,
    pe: 4619,
    grade: "D",
    score: 36,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "Marsh & Mclennan Agency Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3457394,
      d_chronic: 0,
      d_broker: 34675,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "953797439",
  },
  {
    rank: 77,
    name: "Mc Dean Inc",
    state: "VA",
    city: "Tysons",
    emp: 5708,
    total: 3477560,
    pe: 609,
    grade: "D",
    score: 28,
    carrier: "",
    vsm: "",
    broker: "Employee Family Protection Inc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3205434,
      d_broker: 272126,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "540831614",
  },
  {
    rank: 78,
    name: "Vitalmd Group Holding Llc",
    state: "FL",
    city: "Miami",
    emp: 1761,
    total: 3443342,
    pe: 1955,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Digital Insurance Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3014151,
      d_broker: 429191,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "542129332",
  },
  {
    rank: 79,
    name: "Virco Mfg Corporation",
    state: "CA",
    city: "Torrance",
    emp: 752,
    total: 3439101,
    pe: 4573,
    grade: "D",
    score: 36,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3439101,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "951613718",
  },
  {
    rank: 80,
    name: "Spectrum Health System",
    state: "MI",
    city: "Grand Rapids",
    emp: 57864,
    total: 3399278,
    pe: 59,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Custom Benefit Programs Inc.",
    dom: "d_broker",
    domLabel: "Broker",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 3399278,
      d_wage: 0,
    },
    note: "",
    aka: "Corewell Health (filed as Spectrum Health System)",
    cav: "",
    ein: "383382353",
  },
  {
    rank: 81,
    name: "Peapack Gladstone Bank",
    state: "NJ",
    city: "Bedminster",
    emp: 577,
    total: 3386635,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3386635,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "222491488",
  },
  {
    rank: 82,
    name: "Schonfeld Strategic Advisors, Llc",
    state: "NY",
    city: "New York",
    emp: 575,
    total: 3374896,
    pe: 5869,
    grade: "D",
    score: 48,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3374896,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "475082310",
  },
  {
    rank: 83,
    name: "Forfeiture Support Associates, Llc",
    state: "VA",
    city: "Herndon",
    emp: 928,
    total: 3371753,
    pe: 3633,
    grade: "D",
    score: 36,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3371753,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "510476024",
  },
  {
    rank: 84,
    name: "C.R. England, Inc.",
    state: "UT",
    city: "Salt Lake City",
    emp: 1347,
    total: 3364456,
    pe: 2498,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services, Inc.",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3221355,
      d_broker: 143101,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "870257969",
  },
  {
    rank: 85,
    name: "Nhs Management, Llc",
    state: "AL",
    city: "Tuscaloosa",
    emp: 4908,
    total: 3331651,
    pe: 679,
    grade: "D",
    score: 52,
    carrier: "",
    vsm: "",
    broker: "Lockton Companies, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3163661,
      d_broker: 167990,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "020646132",
  },
  {
    rank: 86,
    name: "Breeze Aviation, Inc.",
    state: "UT",
    city: "Salt Lake City",
    emp: 1202,
    total: 3295208,
    pe: 2741,
    grade: "D",
    score: 53,
    carrier: "",
    vsm: "",
    broker: "Marsh And Mclennan Agency, Llc",
    dom: "d_wage",
    domLabel: "Wage",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 1530495,
      d_wage: 1764713,
    },
    note: "",
    aka: "Breeze Aviation Group, Inc.",
    cav: "",
    ein: "822644964",
  },
  {
    rank: 87,
    name: "Plastic Express",
    state: "CA",
    city: "City Of Industry",
    emp: 617,
    total: 3294435,
    pe: 5339,
    grade: "D",
    score: 36,
    carrier: "Aetna",
    vsm: "1.32",
    broker: "Digital Insurance Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 2821709,
      d_chronic: 402199,
      d_broker: 70527,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "953255467",
  },
  {
    rank: 88,
    name: "Jrn, Inc.",
    state: "TN",
    city: "Columbia",
    emp: 489,
    total: 3293419,
    pe: 6735,
    grade: "D",
    score: 44,
    carrier: "",
    vsm: "1.45",
    broker: "Digital Insurance Llc",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 2870129,
      d_chronic: 399263,
      d_broker: 24027,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "620881692",
  },
  {
    rank: 89,
    name: "Nexion Health Management, Inc.",
    state: "MD",
    city: "Sykesville",
    emp: 2663,
    total: 3257674,
    pe: 1223,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Hotchkiss Insurance Agency, Llc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2399322,
      d_broker: 57936,
      d_wage: 800416,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "522238971",
  },
  {
    rank: 90,
    name: "Florida Health Sciences Center, Inc.",
    state: "FL",
    city: "Tampa",
    emp: 15924,
    total: 3250697,
    pe: 204,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Gallagher Benefit Services, Inc.",
    dom: "d_broker",
    domLabel: "Broker",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 3250697,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "593458145",
  },
  {
    rank: 91,
    name: "Houchens Food Group, Inc.",
    state: "KY",
    city: "Bowling Green",
    emp: 2363,
    total: 3241156,
    pe: 1372,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Houchens Insurance Group, Inc",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 2570640,
      d_broker: 15365,
      d_wage: 655151,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "610395075",
  },
  {
    rank: 92,
    name: "Battle Motors, Inc",
    state: "OH",
    city: "New Philadelphia",
    emp: 545,
    total: 3198815,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3198815,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "861232286",
  },
  {
    rank: 93,
    name: "Spatial Front, Inc.",
    state: "MD",
    city: "Bethesda",
    emp: 544,
    total: 3192945,
    pe: 5869,
    grade: "D",
    score: 36,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3192945,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "263662778",
  },
  {
    rank: 94,
    name: "Tata America International Corporation",
    state: "NY",
    city: "New York",
    emp: 33206,
    total: 3189649,
    pe: 96,
    grade: "C",
    score: 58,
    carrier: "",
    vsm: "",
    broker: "Mercer Health And Benefits, Llc",
    dom: "d_broker",
    domLabel: "Broker",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 3189649,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "132805758",
  },
  {
    rank: 95,
    name: "Amity Foundation",
    state: "CA",
    city: "Los Angeles",
    emp: 891,
    total: 3189375,
    pe: 3580,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Heffernan Insurance Brokers",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3174996,
      d_chronic: 0,
      d_broker: 14379,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "770418201",
  },
  {
    rank: 96,
    name: "Kyowa Kirin, Inc.",
    state: "NJ",
    city: "Princeton",
    emp: 536,
    total: 3171893,
    pe: 5918,
    grade: "D",
    score: 36,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "Mercer Health & Benefits, Llc.",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3145990,
      d_chronic: 0,
      d_broker: 25903,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "752778549",
  },
  {
    rank: 97,
    name: "Mmr Group, Inc.",
    state: "LA",
    city: "Baton Rouge",
    emp: 2790,
    total: 3160681,
    pe: 1133,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3160681,
      d_broker: 0,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "721271030",
  },
  {
    rank: 98,
    name: "Team Tag Services, Llc",
    state: "IL",
    city: "Chicago",
    emp: 3329,
    total: 3145550,
    pe: 945,
    grade: "D",
    score: 46,
    carrier: "",
    vsm: "",
    broker: "Mercer Health & Benefits, Llc",
    dom: "d_wage",
    domLabel: "Wage",
    parts: {
      d_carrier: 0,
      d_chronic: 0,
      d_broker: 1475082,
      d_wage: 1670468,
    },
    note: "",
    aka: "",
    cav: "",
    ein: "881639559",
  },
  {
    rank: 99,
    name: "Creative Solutions In Healthcare",
    state: "TX",
    city: "Fort Worth",
    emp: 10545,
    total: 3143703,
    pe: 298,
    grade: "D",
    score: 54,
    carrier: "",
    vsm: "",
    broker: "Ms Benefits",
    dom: "d_chronic",
    domLabel: "Vol. benefit",
    parts: {
      d_carrier: 0,
      d_chronic: 3027130,
      d_broker: 116573,
      d_wage: 0,
    },
    note: "",
    aka: "",
    cav: "short_panel",
    ein: "752887230",
  },
  {
    rank: 100,
    name: "Proud Moments Licensed Behavior -Analysts Pllc, Proud Moments Aba",
    state: "NY",
    city: "New York",
    emp: 533,
    total: 3128382,
    pe: 5869,
    grade: "D",
    score: 28,
    carrier: "Cigna",
    vsm: "1.45",
    broker: "",
    dom: "d_carrier",
    domLabel: "Network",
    parts: {
      d_carrier: 3128382,
      d_chronic: 0,
      d_broker: 0,
      d_wage: 0,
    },
    note: "Multiple-employer plan \u2014 participants span several employers",
    aka: "",
    cav: "",
    ein: "470986503",
  },
];
